backend:
  name: git-gateway
  branch: main # หรือ branch ที่ deploy อยู่

media_folder: "static/uploads" # เก็บไฟล์รูป
public_folder: "/uploads"

collections:
  - name: "news"
    label: "ข่าวสารและกิจกรรม"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "หัวข้อ", widget: "string" }
      - { name: "image", label: "รูปภาพ", widget: "image" }

  # 2) หมู่บ้านที่ดูแล
  - name: "villages"
    label: "หมู่บ้านที่ดูแล"
    folder: "content/villages"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "ชื่อหมู่บ้าน", widget: "string" }
      - { name: "image", label: "รูปหมู่บ้าน", widget: "image" }
